### ISSUE TITLE
inconsistent variable name (OPENAI_API_KEY, SERPER_KEY)

### ISSUE THREAD

**Issue by Yingjia-Wan** [Yixiao-Song/VeriScore#1]
Hi! I would like to express great appreciation for your work. Love the paper and your code implementation.

I found a tiny issue of an inconsistent variable name: 

1. In README.md the instruction was: `export OPENAI_API_KEY={your_openai_api_key}`, but in the code script `get_response.py` the env variable to access the key is `OPENAI_API_KEY_PERSONAL` (as shown in the screenshot).
<img width="1116" alt="image" src="https://github.com/Yixiao-Song/VeriScore/assets/119270722/201dc433-17a3-42d9-88c7-392eaf9dd330">

2. The same goes to `SERPER_KEY` where the env variable is written as `SERPER_KEY_PRIVATE`:
<img width="689" alt="image" src="https://github.com/Yixiao-Song/VeriScore/assets/119270722/3997cdf9-a44f-4674-9ffd-925e450f3c40">

**Comment by mungg** [comment]
Thanks for the heads-up!
You are correct that `OPENAI_API_KEY_PERSONAL` and `SERPER_KEY_PRIVATE` are the appropriate keys. I have updated the README.md file accordingly. Thank you once again!
