### ISSUE TITLE
Long-form data used in VeriScore

### ISSUE THREAD

**Issue by jacqueline-he** [Yixiao-Song/VeriScore#3]
Hi, thanks for the great work! 
For replication purposes, I'm wondering how / whether we could access the long-form datasets that are included in Table 1, in particular LongFact (which is somewhat costly to re-generate) and FreshBooks (which seems unique to the current paper). Thanks!! 
Jacqueline

**Comment by Yixiao-Song** [comment]
Hi Jacqueline,

Thank you for your email! I have uploaded the data in this folder
<https://drive.google.com/drive/folders/1hzazGn9gxBNgkaYsHlqdfB5pxq_8RKt6?usp=sharing>.
Please let me know if there is any issue accessing it.

Best,
Yixiao

**Comment by jacqueline-he** [comment]
Thank you for the prompt response!!
